baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

# params:
#   title: "Hugo Profile"
#   description: Text about my cool site
#   # staticPath: ""  # The path to serve the static files from
#   favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello there! I'm"
    title: "Sreenivas Sagili."
    content: "A passionate programmer with experience in Software Development & Big Data Analytics who loves to build Microservices and develop API's."
    image: /images/sreeni.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1wJ3ti7mMu2ZwYoQfs0y5HvGW6TuwKLrX/view?usp=sharing"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/Sreenivas-Reddy-S"
        - icon: fab fa-twitter
          url: "https://www.twitter.com/@Cnu_Die"
        - icon: fab fa-linkedin-in
          url: "https://www.linkedin.com/in/sagili-sreenivas-reddy-74a490129/"

  # About
  about:
    enable: true
    title: "Eager to Contribute from December 2023!"
    image: "/images/sree.png"
    content: |-
      Currently, working as a Graduate Teaching Assitant at RIT in Big Data Analytics. A Masters in Computer Science student with 4+ years of professional experience in Java, Spring boot, Spring, Python, FLask, Go, NodeJS, SQL. 
      I have a strong interest in the the intersection of Technology and Business. Skills:
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "JAVA, SPRING"
        - "PYTHON, FLASK"
        - "HTML, CSS"
        - "JavaScript, NodeJS"
        - "SQL, MongoDB"
        - "AWS Cloud" 

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:

      - job: "Graduate Teaching Assiatant"
        company: "RIT"
        companyUrl: "https://www.rit.edu"
        date: "Jan 2022 - Present"
        # info:
        #   enable: false
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        content: |-
          - Assisted 60 students in answering technical questions, evaluated their insights, math & analysis on assignments based on the correctness and runtime of their algorithms(classification, clustering) in Big Data Analytics.
          - Designed and evaluated quizzes to reinforce students learning of skills and through weekly check-ins.
          - Empowered students in seamless data sharing within Hadoop clusters on AWS S3 and facilitated ad-hoc data democratization initiatives.

      - job: "Software Developer"
        company: "Home Credit India Finance Pvt Ltd"
        companyUrl: "https://www.homecredit.co.in/en"
        date: "Jun 2019 - Jul 2021"
        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "https://example.com"
        content: |-
          - As a backend developer, Implemented best practices for various Web API's & Data API's of a micro-services system using Java, Spring, Spring Boot and integrated using MuleSoft Anypoint studio by utilizing the internal framework(SDLC).Testing: 100% Unit tests coverage.
          - Integrated API's to existing front end application using ReactJs. Setup CI/CD pipeline using Jenkins to auto-deploy the API's in different environments which improved teams efficiency by 30%.
          - Collaborated effectively with third party vendors to consume their API endpoints and integrate it.
          - Refactored 5 legacy java applications from Java 6 to Java 11.

      - job: "Software Developer Intern"
        company: "Assent Technologies"
        companyUrl: "https://assenttec.com"
        date: "Jan 2018 - Jun 2018"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        # info:
        #   enable: true
        #   content: I worked as a software developer for more than one year in Amazon.
        content: |-
          - "Programmed different modules for a medical application using Python & SQL." 
          - "Wrote and tested code, improved functionalities & reliability of existing system by 36% reducing complexities, duplications and potential bugs."
          - "Created several data visualizations for medical data using D3.js."
          - "Performed web scraping on more than 100 websites to generate datasets as a part of the product roadmap."


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master's in Computer Science"
        school:
          name: "Rochester Institute Of Technology, New York"
        date: "2021 - 2023"
        GPA: "3.5 out of 4.0"
        content: |
          - Worked as a Graduate Teaching Assistant for Big Data Analytics at Rochester Institute Of Technology.
          - Relevant Academic Coursework: Data Structures and Algorithms, Advanced Object-Oriented Programming, Problem-Solving, Big Data Analytics, NoSQL/NewSQL Databases, Natural language processing, Distributed Systems, Machine Learning, Web Services & System Programming.
          Extracurricular Activities
            - Worked as a research volunteer and supported several projects in Big data Analytics under Prof Kinsman. 
            - Assistant Vice President of Rotract club from 2016-2017.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Vellore Institute of Technology, Vellore"
        date: "2015 - 2019"
        GPA: "8.4 out of 10.0"
        content: |
          - Won 2nd price in a Tech Workship conducted in VIT by IEEE club.
          - Computer Science Courses: Web Progromming, Cloud Computing, Cryptography and Network Security, Computer Programming, Data Structures, Computer Networks, Computer Architecture, Compiler Design, IoT (Internet of Things), Operating Systems, Distributed and Parallel Computing, High Performance Computing, Theory of Computation, Object Oriented Analysis and Design.
          - Data Science Courses: Artificial Intelligence, Web Mining, Big Data Analytics, Content based image analysis, Database Management.
          Extracurricular Activities
            - Worked as a research volunteer and supported several projects in Deep Learning under Prof Anuradha. 
            - Exemplarily served as the Elected Cultural Association Club Secretary from 2017-2018.


    # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Stock Price Prediction
        content: "To predict the prices of stock at the smallest level of granularity using Artificial Neural Networks. Containerized extensible data ingestion, with out of the box implementation for the stock data and a neural network based model LSTM, well suitable for the time series data."
        image: /images/projects/stock-price-prediction.jpeg
        links:
          - icon: fab fa-github
            url: https://drive.google.com/drive/folders/1KI1Ccgs19_ZMd5BVcPIlBAZay7IWdyY-?usp=sharing
       

      - title: Web Service Recommendation
        content: Recommending a Web Service by incorporating User related, Service related and Topic related Latent latent factors.
        image: /images/projects/web_service_recommendation.png
        links:
          - icon: fab fa-github
            url: https://docs.google.com/presentation/d/1lhntC8iRHuMkfNZ16FjbVsKkMZTjtnwT/edit?usp=share_link&ouid=104675213338128089020&rtpof=true&sd=true

      - title: Ecommerce Database Using SQL & NoSQL
        content: An E-commerce application developed by leveraging the transactional properties from SQL & faster data retrival properties from MongoDB.
        image: /images/projects/SQL_MongoDB.jpeg
        links:
          - icon: fab fa-github
            url: https://docs.google.com/presentation/d/1mkWo-2B44k_dTWMj3269Yly5kmdSMetn/edit?usp=share_link&ouid=104675213338128089020&rtpof=true&sd=true


  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: AWS Developer Associate
        content: Certified Amazon Web Services Developer Associate by Amazon.
        image: /images/projects/AWS-Certified-Developer-Associate_badge.png
        url: https://www.credly.com/badges/ecfb59be-1fed-4d7b-af92-c3cc4988e10a/public_url
      - title: Microsoft Azure Developer Associate
        content: Certified AMicrosoft Azure Developer Associate by Microsoft.
        image: /images/projects/azure-developer-associate.png
        url: https://www.credly.com/badges/a3ecea97-a321-46e3-b750-c97d32825ee3
      - title: Connect Four
        content: Developed a web application, connect four using JAVA & Multi-Threading and deployed it on AWS EC2 instance.
        image: /images/projects/connect-four.jpeg
      - title: Cross Functional Training
        content: Awarded with the First Prize in the Cross Functional Training at Home Credit India Finance Pvt Ltd.
        image: /images/projects/web_service_recommendation.png

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: You can email me to get in touch with me. My inbox is always open. 
    email: srinu7529@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: "https://github.com/Sreenivas-Reddy-S"
      linkedin: https://www.linkedin.com/in/sagili-sreenivas-reddy-74a490129/
      twitter: "https://www.twitter.com/@Cnu_Die"
      

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"